# NumPy Basics

In [3]:
# numpy operations perform much better than operations on 'native' types
import numpy as np

my_array = np.arange(10000000)
my_list = list(range(10000000))

%time for _ in range(10): my_array2 = my_array * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 133 ms
Wall time: 6.17 s


## 1 Creating ndarrays

In [6]:
# import numpy and create a random 2x3 array
import numpy as np

data = np.random.randn(2,3)
data

array([[-1.83050802,  0.22518091,  0.62080631],
       [-0.10620753,  0.87801279, -0.37030143]])

In [7]:
# multiply each vaue by 10
data * 10

array([[-18.30508022,   2.25180915,   6.2080631 ],
       [ -1.06207527,   8.78012788,  -3.70301432]])

In [8]:
# add each value to itself
data + data

array([[-3.66101604,  0.45036183,  1.24161262],
       [-0.21241505,  1.75602558, -0.74060286]])

In [10]:
# each multidimensional array has to main features
# the `shape` (size of each dimension) and `dtype`, the data type for all entries
# note that the data type applies to ALL elements in the array
print(data.shape)
print(data.dtype)

(2, 3)
float64
